import './../blocks/logo/logo.js'
import './../blocks/vk/vk.js'
import './../blocks/git/git.js'
import './../blocks/centerText/centerText.js'
import './../blocks/menuIcon/menuIcon.js'
import './../blocks/menu/menu.js'
import './../blocks/about/about.js'
import './../blocks/button/button.js'